export * from "./Header.jsx"
export * from "./Nav.jsx"
export * from "./BackgroundHeader.jsx"
export * from "./Soluciones.jsx"
export * from "./Main.jsx"
export * from "./Equipos.jsx"
export * from "./Lideres.jsx"
export * from "./Contacto.jsx"